### ISSUE TITLE
Для метода map To добавить дженерик результата, для возможности его указать явно.

### ISSUE THREAD

**Issue by QwiniTRON** [alt-point/active-models#19]
Для метода map To добавить дженерик результата, для возможности его указать явно. В связи с невозможность его статически вычислить. 

По причине наличия косвенных указателей на целевую структуру(строка с указанием на некий класс, то есть он будет возвращён мап функцией). Лучше иметь возможность явно указать желаемый тип. Либо поддерживать только константные значения и конкретные классы. Тогда тип можно будет вычислить.

**Comment by altpoint** [comment]
пример вызова, куда и что ты предлагаешь добавить
