### ISSUE TITLE
Добавить возможность передавать произвольный payload в функцию мапа.

### ISSUE THREAD

**Issue by QwiniTRON** [alt-point/active-models#20]
Добавить возможность передавать произвольный payload в функцию мапа. Для некоторых специфичных преобразований может понадобиться дополнительный контекст. Так многие преобразования можно будет обобщить и переиспользовать. 

Например: передать вспомогательный сервис или предыдущее состояние для для маппинга более подходящего значения. Хотя кажется, что такие случаи будут очень редки. И большая часть закроется либо значениями по-умолчанию либо отдельным шагом подготовки модели.

**Comment by altpoint** [comment]
покажи пример кода, как ты хочешь это видеть и как использовать, не совсем пока тебя понимаю
