### ISSUE TITLE
Заложить возможность частичного обновления.

### ISSUE THREAD

**Issue by xhnrdt00n** [alt-point/active-models#7]
Заложить возможность для частичного обновления.

Возможное решение:
внедрить old_attributes/original_attributes,  куда записываются оригинальные атрибуты, attributes/current_attributes где хранятся текущие значения. getter dirty который будет возвращать обновленные/грязные атрибуты.

**Comment by xhnrdt00n** [comment]
![изображение](https://user-images.githubusercontent.com/55158446/140927475-c5598908-5feb-48a5-b412-4a753e326a7c.png)

**Comment by altpoint** [comment]
Closed by v3.0.2
